/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 public\marble_bust\marble_bust_01_4k.gltf -t -r public
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    marble_bust_01: THREE.Mesh
  }
  materials: {
    marble_bust_01: THREE.MeshStandardMaterial
  }
}

export function Bust(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/marble_bust/marble_bust_01_4k.gltf') as GLTFResult
  return (
    <group {...props} dispose={null} scale={20}>
      <mesh geometry={nodes.marble_bust_01.geometry} material={materials.marble_bust_01} position={[0, 0.03, 0]} />
    </group>
  )
}

useGLTF.preload('/marble_bust/marble_bust_01_4k.gltf')
